# Generated by Django 3.1.7 on 2021-04-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210410_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(default='', max_length=80)),
                ('phone', models.CharField(default='', max_length=80)),
                ('desc', models.CharField(default='', max_length=800)),
            ],
        ),
    ]
