# Generated by Django 3.1.7 on 2021-04-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
